### ISSUE TITLE
Audio and video not in sync (Raspberry Camera + USB Mic)

### ISSUE THREAD

**Issue by romansey** [datarhei/restreamer#170]
I'm running the latest (as of today) Docker image of Restreamer on a Raspberry PI 3B+ using the Raspberry Camera. I recently connected a USB microphone and set up Restreamer to use that audio device. Everything works except that the video channel is lagging behind the audio channel for ~5 seconds. I could not find any audio delay options or similar that would help reduce or eliminate the delay.

This is my Docker-Compose configuration. Video codec is set to "copy", audio codec is set to "auto".

```
version: '3'
services:
  restreamer:
    container_name: restreamer
    image: datarhei/restreamer-armv7l:0.6.5
    privileged: true
    restart: always
    environment:
      - RS_USERNAME=admin
      - RS_PASSWORD=****
      - RS_MODE=RASPICAM
      - RS_RASPICAM_BITRATE=15000000
      - RS_RASPICAM_WIDTH=1280
      - RS_RASPICAM_HEIGHT=1024
      - RS_RASPICAM_SATURATION=-100
      - RS_RASPICAM_CONTRAST=-7
      - RS_RASPICAM_AUDIO=true
      - RS_RASPICAM_AUDIODEVICE=1
    ports:
      - 8080:8080
    devices:
      - /dev/snd
    tmpfs:
      - /tmp/hls
    volumes:
      - ./data/restreamer-config:/restreamer/db
      - /opt/vc:/opt/vc
```

If there are any possibilities to eliminate the delay, I would gladly appreciate your help. :)
