### ISSUE TITLE
NGINX reverse proxy config for RTMP?

### ISSUE THREAD

**Issue by wallopthecat** [datarhei/restreamer#176]
Goals
1. Multiple instances of restreamer on same host behind nginx with https
2. Must be able to listen on RTMP for each instance (prerequisite was getting env variable [custom RTMP ports](https://github.com/datarhei/restreamer/pull/175) done)
3. ~View counts with `--with-http_stub_status_module`~ [Done here](https://github.com/wallopthecat/restreamer/tree/status)

While trying to add [custom RTMP ports](https://github.com/datarhei/restreamer/pull/175) so I can run multiple streams from the same host, I've run into some issues that stem from my lack of understanding of nginx. These two RTMP ports (1935, 1936) are punched through NAT but I am missing something fundamental, because I cannot stream to `mysite.com/live` - I have to stream to the internal host IP directly - `rtmp://192.168.192.2/live` works but `rtmp://mysite.com/live` does not. 

Can any nginx wizards help me understand what is missing to get a solid reverse proxy conf that works with multiple instances and RTMP? 

using `linuxserver/letsencrypt` in front of restreamer. The server block for restreamer instance 1 is below - instance 2 is a dupe but on a subdomain. There are definitely optimizations to be had, which is why I am here
```
## Version 2019/08/01 - Changelog: https://github.com/linuxserver/docker-letsencrypt/commits/master/root/defaults/default

# redirect all traffic to https
server {
	listen 80;
	listen [::]:80;
	server_name mysite.com;
	return 301 https://$host$request_uri;
}

# main server block
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;
	root /config/www/mysite.com;
	index index.html;
	server_name mysite.com;
	include /config/nginx/ssl.conf;
	client_max_body_size 0;

	location / {
		try_files $uri $uri/ /index.html =404;
	}

	location /restreamer {
		return 301 $scheme://$host/restreamer/;
	}

	location ^~ /restreamer/ {
	    rewrite ^/restreamer(/.*)$ $1 break; # remove "restreamer" from the redirect so the app server is just raw http://app:port
		include /config/nginx/proxy.conf;
		resolver 127.0.0.11 valid=30s;
		proxy_pass http://restreamer:8080;
	}
        # does this need to be a TCP proxy? can only stream to rtmp://LOCALIP/live
	location ^~ /live {
		include /config/nginx/proxy.conf;
		resolver 127.0.0.11 valid=30s;
		proxy_pass http://restreamer:8080;
	}
        # --with-http_stub_status_module for hacky view count
	location ^~ /status {
		include /config/nginx/proxy.conf;
		resolver 127.0.0.11 valid=30s;
		proxy_pass http://restreamer:8080/status;
	}
}
```

Docker compose:
```
 restreamer:
    image: restreamer-custom-rtmp-port
    container_name: restreamer
    ports:
      - 1935:1935
    volumes:
      - "${DOCKERCONFDIR}/restreamer/db:/restreamer/db"
    environment:
    ...
      - RS_RTMP_PORT=1935
 restreamer2:
    image: restreamer-custom-rtmp-port
    container_name: restreamer2
    ports:
      - 1936:1936
    volumes:
      - "${DOCKERCONFDIR}/restreamer2/db:/restreamer/db"
    environment:
    ...
      - RS_RTMP_PORT=1936
```

EDIT: will try 
```
server {
 listen 1935;
    proxy_pass restreamer:1935;
          proxy_protocol on;
}

and in the other subdomain
server {
 listen 1936;
    proxy_pass restreamer2:1936;
          proxy_protocol on;
}
```
