### ISSUE TITLE
Error Index.html in v2.0

### ISSUE THREAD

**Issue by Inzombie** [datarhei/restreamer#326]
Hi, i'm trying to install via Docker an error appears. 

{"code":404,"message":"File not found","details":["/index.html"]}

Any suggestion?

**Comment by matigumma** [comment]
Hi there, im getting the same 404 in /ui
inpage.js file loaded but get "404 page not found" at body page

**Comment by matigumma** [comment]
im using docker-compose
```

  defaultstreamer:
    container_name: "defaultstreamer"
    restart: always
    image: datarhei/restreamer:2.0.0
    environment:
      - CORE_API_AUTH_PASSWORD=xxxxxxx
      - CORE_API_AUTH_USERNAME=admin
    volumes:
      - ./config-rs/restreamer/db:/core/config
      - ./config-rs/restreamer/data:/core/data
```
