### ISSUE TITLE
Can't get my docker-compose.yaml to work properly.

### ISSUE THREAD

**Issue by Nostradamus1973** [datarhei/restreamer#598]
Good afternoon,

**Subject of the issue**
Describe your issue here.

Can't get my docker-compose.yaml to work properly.

**Your environment**
Explain your setup so we can better understand what's going on.

Kubuntu 23.04 running in a VM that has it own bridged nic card that accesses a VPN(Italy) which are all in working order. I use Portainer to access my compose files from a web browser like Chrome or Firefox.
**Files**
Add the Restreamer [Process-Report](https://www.youtube.com/watch?v=mZMGrweFCsM), the  [Publication-Service Process-Report](https://youtu.be/7z95qnafzLo) or a list of relevant files for this issue. This will help us navigate the project and explain where to start. 

Here's my docker-compose.yaml :
```
version: "3.4"
services:
   restreamer:
     container_name: restreamer
     environment:
       - PGID=1000
       - PUID=1000
       - TZ=America/New_York
     image: ghcr.io/datarhei/restreamer:latest
     ports:
       - 8080:8080       # Web Interface Port
       - 8181:8181       # Port used to
       - 1936:1936       # Port for
       - 1937:1937       # Port for
       - 6000:6000/udp   # UDP Port for
     volumes:
      # - logs:/var/log/restreamer
       - /home/nostradamus/dockers/restreamer:/app/data/
       - /home/nostradamus/dockers/restreamer/data:/core/data
     restart: unless-stopped

```
**Steps to reproduce**
Tell us how to reproduce this issue.   Reloading the docker compose over and over again produces the same error that it can not deploy the stack/container.

If the Restreamer has problems processing your video signals, it would be constructive if you send us this origin stream by mail with the GitHub issue number to support@datarhei.com. This way, we can better see why the Restreamer is not working correctly.
N/A in this instance

**Expected behavior**
Tell us what should happen
Portainer should accept the docker compose file, however it does not.
**Actual behavior**
Tell us what happens instead
An error stating it can not deploy it's stack.

## Business inquiries
**We provide support for commercial requirements with professional support, agile software development, and consulting.** If you have a commercial request, be it a bug or a feature enhancement, please contact us directly at support@datarhei.com.

Thank you for your help and time.
Have a nice day.

EDIT:

I added PGID and PUID along with core/data directory and now Portainer seems to hang during the deployment.
