### ISSUE TITLE
Docker Compose with enconding nvidia cuda (NVENC) support

### ISSUE THREAD

**Issue by danielgoz** [datarhei/restreamer#795]
Hi there.

I love the app but it is killing my CPU :-(

I am running it in docker with nvidia toolkit  (other containers i.e frigate using the gpu all good)

how should I set my docker compose to enable NVENC encoding?

my current docker compose:

```
version: '3.3'
services:
    restreamer:
        container_name: restreamer
        volumes:
            - './config:/core/config'
            - './data:/core/data'
        ports:
            - '8080:8080'
            - '8181:8181'
            - '1935:1935'
            - '1936:1936'
            - '6000:6000/udp'
        restart: always
        image: 'datarhei/restreamer:cuda-latest'
        runtime: nvidia
        environment:
          - NVIDIA_DRIVER_CAPABILITIES=all
          - NVIDIA_VISIBLE_DEVICES=all
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  capabilities: [gpu]
        devices:
          - /dev/dri:/dev/dri
```

Thanks

**Comment by danielgoz** [comment]
figured it out.
it should be:

```
version: '3.3'
services:
    restreamer:
        container_name: restreamer
        volumes:
            - './config:/core/config'
            - './data:/core/data'
        ports:
            - '8080:8080'
            - '8181:8181'
            - '1935:1935'
            - '1936:1936'
            - '6000:6000/udp'
        restart: always
        image: 'datarhei/restreamer:cuda-latest'
        runtime: nvidia
```

now, how do I know if it is indeed using the GPU.
I can see this in nvidia-smi:

`|    0   N/A  N/A    247564      C   /usr/local/bin/ffmpeg                         306MiB |`

is that it?
